### ISSUE TITLE
[误杀] AdRules AdBlock List Full

### ISSUE THREAD

**Issue by chermy** [Cats-Team/AdRules#100]
*$3p
这个规则太大了, 连github umbrella sogou 等大站全部拦截. 
![1](https://user-images.githubusercontent.com/5954008/206908749-05c08bf0-15dc-42ff-b299-4e6fc565a1b4.png)
![2](https://user-images.githubusercontent.com/5954008/206908838-efcb5a64-a641-4106-b1f1-e42aa977ef42.png)

关掉规则后正常.

**Comment by hacamer** [comment]
@chermy 没有找到这条规则喔 有可能是没更新完整 你更新下规则试试？
