### ISSUE TITLE
建议去除adguard dns

### ISSUE THREAD

**Issue by biange200** [Cats-Team/AdRules#101]
你的cats-team domain dns内置的adguarddns会导致卡网 建议去除

**Comment by hacamer** [comment]
@biange200 请详细描述你的问题（不少于50字）

**Comment by biange200** [comment]
比如说看抖音视频 有时候会卡着需要缓冲很久 有时候小红书 酷安图片无法加载或是慢
关闭了正常



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月13日 19:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Cats-Team/AdRules] 建议去除adguard dns (Issue #101) |

@biange200 请详细描述你的问题（不少于50字）

**Comment by hacamer** [comment]
@biange200 加载慢和无法加载 请具体举例 并提供使用的工具 最好附上截图

**Comment by biange200** [comment]
从 网易邮箱大师 发来的云附件
|
| |
| |
|
| |
| SVID_20221213_200959_1.mp4 |
| |
| (7.5M,2022年12月28日 20:18 到期) |
| |
| 下载 |
| |
| |



用的是rethinkdns 刚刚用抖音极速版录屏的 你看是不是卡着



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月13日 20:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Cats-Team/AdRules] 建议去除adguard dns (Issue #101) |

@biange200 加载慢和无法加载 请具体举例 并提供使用的工具 最好附上截图

**Comment by hacamer** [comment]
> 从 网易邮箱大师 发来的云附件 | | | | | | | | | SVID_20221213_200959_1.mp4 | | | | (7.5M,2022年12月28日 20:18 到期) | | | | 下载 | | | | | 用的是rethinkdns 刚刚用抖音极速版录屏的 你看是不是卡着 | | ***@***.*** | | ***@***.*** |
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年12月13日 20:09 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [Cats-Team/AdRules] 建议去除adguard dns (Issue #101) | @biange200 加载慢和无法加载 请具体举例 并提供使用的工具 最好附上截图 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

看不见的，。

**Comment by biange200** [comment]
我想问下你 adguardAPP 内置DNS规则 就叫adguard dns很多人都是关闭或是用其他的dns规则吧 你自己应该也是关闭的
如果用过都知道这个adguard自家的DNS在国内卡网
![Screenshot_20221213_201242.jpg](https://user-images.githubusercontent.com/37582806/207318221-01075db7-0b94-4798-a59b-7f5294ab1cf4.jpg)https://user-images.githubusercontent.com/37582806/207318239-59aa96e2-8a41-4b9e-bc2d-6035a2cf77d6.mp4

**Comment by hacamer** [comment]
@biange200 But 我没加这个规则 至于卡网 我也没遇到过

**Comment by biange200** [comment]
> @biange200 But 我没加这个规则 至于卡网 我也没遇到过

![Screenshot_20221213_204015.jpg](https://user-images.githubusercontent.com/37582806/207320707-675dc11f-4653-4a99-b716-53504dfc4ad9.jpg)
这不是你自己加的?DNS list里

**Comment by biange200** [comment]
> @biange200 But 我没加这个规则 至于卡网 我也没遇到过

你平时用的是abp规则吧 你adguard规则没问题不卡网 因为adguard官方的abp规则也不卡网 但DNS规则会卡网 所以这也是很多人都是用的adguard的内容拦截没用dns拦截吧

**Comment by hacamer** [comment]
> > @biange200 But 我没加这个规则 至于卡网 我也没遇到过
> 
> ![Screenshot_20221213_204015.jpg](https://user-images.githubusercontent.com/37582806/207320707-675dc11f-4653-4a99-b716-53504dfc4ad9.jpg) 这不是你自己加的?DNS list里

你确定？？ 你打开过了？？

**Comment by biange200** [comment]
确定 我这不是在你的github里面找到的? 我之前用过adguard 知道adguard自带的DNS规则卡网 结果用你的规则也卡网 我就想你abp规则有adguard的 那DNS规则肯定也有adguard家的 
最后我就在你的规则上游找到了

**Comment by hacamer** [comment]
> 确定 我这不是在你的github里面找到的? 我之前用过adguard 知道adguard自带的DNS规则卡网 结果用你的规则也卡网 我就想你abp规则有adguard的 那DNS规则肯定也有adguard家的 最后我就在你的规则上游找到了

@biange200 你真确定这个源就是AdGuard的？？ 看清楚了
![image](https://user-images.githubusercontent.com/73057402/207328055-a75f8a62-ddd5-468e-a4e4-fbef5779ff73.png)
https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
真确定是？？

**Comment by biange200** [comment]
你的意思是说你的dns规则没有adguard家的DNS官方规则?  只有abp的规则包含了?

**Comment by hacamer** [comment]
项目中没有任何一个规则包含adg的DNS规则

-------- 原始郵件 --------
在 2022年12月13日 21:23，biange200 寫道：

**Comment by biange200** [comment]
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt![Screenshot_20221213_212457.jpg](https://user-images.githubusercontent.com/37582806/207331367-52be51c4-5293-4b48-9071-eb582b270060.jpg)
是有点区别 可能是我搞错了吧

**Comment by hacamer** [comment]
所以，，，这是rethinkdns的问题 与我无关
