### ISSUE TITLE
[误杀] AdRules AdBlock List Full ( *$3p 规则)

### ISSUE THREAD

**Issue by MaxMadcc** [Cats-Team/AdRules#102]
*$3p
不清楚是什么原因导致这个触发这个规则。

已经更新最新版本。
![QQ截图1](https://user-images.githubusercontent.com/19978097/207377756-51b1fb13-d315-48d5-a0ac-0ff22d4d7211.png)
![QQ截图20221213234301](https://user-images.githubusercontent.com/19978097/207378120-4926a051-af79-4ce0-902b-588e414fccd0.png)
![QQ截图20221213233943](https://user-images.githubusercontent.com/19978097/207377772-1763c6b7-60ea-461b-a63b-7e7dc672b266.png)
uBlock Origin版本
![QQ截图20221213233952](https://user-images.githubusercontent.com/19978097/207377796-baeb54e9-65cb-4494-bb5b-24c228f48225.png)

**Comment by hacamer** [comment]
@MaxMadcc 你现在用的是哪个规则链接

**Comment by MaxMadcc** [comment]
> @MaxMadcc 你现在用的是哪个规则链接

https://cats-team.github.io/AdRules/adblock.txt

**Comment by hacamer** [comment]
如果可以，把ublock中 支持-排错信息 那一堆东西发下

**Comment by MaxMadcc** [comment]
[dump_SNFEDNR.txt](https://github.com/Cats-Team/AdRules/files/10219912/dump_SNFEDNR.txt)

**Comment by hacamer** [comment]
感觉怪怪的 我反馈给uBlock的作者去

**Comment by hacamer** [comment]
修了一下 应该是可以了的 更新规则试试 @MaxMadcc

**Comment by MaxMadcc** [comment]
确实可以了，谢谢
