### ISSUE TITLE
AdRules AdBlock List 誤殺 "||s.yimg.com^"

### ISSUE THREAD

**Issue by pekkle-hksar** [Cats-Team/AdRules#104]
AdRules AdBlock List裡邊有一條 `||s.yimg.com^`
訪問 https://hk.yahoo.com 及 https://hk.news.yahoo.com 時，新聞圖片都出不來了
加了[allow-domains-list.txt](https://github.com/Cats-Team/AdRules/blob/main/allow-domains-list.txt)進adguard (firefox browser plugins)的allowlist，雖然裡邊有s.yimg.com及yahoo.com，但都沒有幫助。

`||s.yimg.com^` 這條也太猛了

**Comment by hacamer** [comment]
https://github.com/damengzhu/banad/commit/7c37447ed8d824327c9deea07afbed00a318bcf1 上游已修復 妳更新規則就行 （GitLink源會遲d 差唔多1日）
附：勿用未在README嘅規則 唔一定啱用(No Instructions)
allow-domains-list is only for AdGuardHome (Allow-List)
