### ISSUE TITLE
ADGuard Filter List被精简了吗？

### ISSUE THREAD

**Issue by mpamxl** [Cats-Team/AdRules#105]
RT，这个规则在手机很好用，是被精简了吗？
AdRules AdBlock List系列在手机不如这个好用，比如汽车之家，AdRules AdBlock List会误杀选车型导致无法弹出车型，还会有些弹窗广告无法删除，ADGuard Filter List不会，可以继续更新吗？

**Comment by hacamer** [comment]
是的，暫無計劃加回 ADG內打開以下過濾器即可

- AdGuard Base filter
- AdGuard Mobile Ads filter
- AdGuard Tracking Protection filter
- AdGuard URL Tracking filter
- AdGuard Social Media filter
- AdGuard Annoyances filter
- AdGuard Chinese filter

**Comment by mpamxl** [comment]
下面哪个是ADGuard Filter List的替代呢？

**Comment by mpamxl** [comment]
还是希望能加回来，感觉很好用，至少比目前其它的好用，为啥要删掉呢。

**Comment by mpamxl** [comment]
顺便问下这些订阅链接在哪？
AdGuard Base filter
AdGuard Mobile Ads filter
AdGuard Tracking Protection filter
AdGuard URL Tracking filter
AdGuard Social Media filter
AdGuard Annoyances filter
AdGuard Chinese filter

**Comment by mpamxl** [comment]
主要是，之前合并好的ADGuard Filter List特别方便，不想单独还装一个APK，可否求加回来，确实比现在的AdRules AdBlock List好用啊

**Comment by hacamer** [comment]
> 还是希望能加回来，感觉很好用，至少比目前其它的好用，为啥要删掉呢。


AdGuard Filter List 唔係本項目嘅核心
因為ADG嘅规则本身有好多註解，而d註解又有對應嘅作用 合併時剔除咗d註解 效果會下降



> 顺便问下这些订阅链接在哪？ AdGuard Base filter AdGuard Mobile Ads filter AdGuard Tracking Protection filter AdGuard URL Tracking filter AdGuard Social Media filter AdGuard Annoyances filter AdGuard Chinese filter

可以去 https://filterlists.com 去搵

> 主要是，之前合并好的ADGuard Filter List特别方便，不想单独还装一个APK，可否求加回来，确实比现在的AdRules AdBlock List好用啊

你可以試下 Lite

**Comment by mpamxl** [comment]
试过Lite，效果还是不如ADGuard Filter List...就有点尴尬...同时想提下...好像现在国内源https://code.gitlink.org.cn很快...可以更新个这个源嘛？

**Comment by hacamer** [comment]
> 试过Lite，效果还是不如ADGuard Filter List...就有点尴尬...同时想提下...好像现在国内源[https://code.gitlink.org.cn很快...可以更新个这个源嘛？](https://code.gitlink.org.cn%E5%BE%88%E5%BF%AB...%E5%8F%AF%E4%BB%A5%E6%9B%B4%E6%96%B0%E4%B8%AA%E8%BF%99%E4%B8%AA%E6%BA%90%E5%98%9B%EF%BC%9F)

gitlink俾現在更新會慢1日

Lite效果唔得？Normal又話誤殺
你主要瀏覽咩網站？偏向國內定係國外？

**Comment by mpamxl** [comment]
是的...客观使用测试结果Lite效果还是不如ADGuard Filter List...平时没有固定...国内国外网站都可能访问...但刚才我用两套规则随意在谷歌搜索了一些可能广告比较多的网站...测试下来综合对比还是ADGuard Filter List去广告效果更好...目前也测试了大萌主的那套规则...效果也不错...对比下来...使用体验比Lite和完整版好...

**Comment by mpamxl** [comment]
所以还是想提下可否暂时保留ADGuard Filter List...可以多个选择...其次Gitlink会慢一天的话...问题不大我觉得...因为他目前作为国内源速度确实不错...

**Comment by mpamxl** [comment]
> 

以前就用这个...但跟你现在保留的一样...会误杀导致比如汽车之家选择车型的时候无法弹出车型列表...

**Comment by mpamxl** [comment]
目前测试了一圈只能先用大萌主的规则啦......
