### ISSUE TITLE
我认为这是一个错误

### ISSUE THREAD

**Issue by 964215963** [Cats-Team/AdRules#124]
![图片](https://user-images.githubusercontent.com/102475890/231146219-762cc124-7ea6-4524-8f38-ca49518ea3c4.png)
![图片](https://user-images.githubusercontent.com/102475890/231146329-b0082853-a918-487e-9b2f-bfd53405bf4c.png)

**Comment by yaozijin** [comment]
不仅如此，还有
.tv^
