### ISSUE TITLE
请问https://cats-team.coding.net/p/adguard/d/AdRules/git/raw/main/allow.txt这个怎么放？

### ISSUE THREAD

**Issue by angelfish110** [Cats-Team/AdRules#13]
请问https://cats-team.coding.net/p/adguard/d/AdRules/git/raw/main/allow.txt这个怎么放？

我用的是安卓版的Adguard！
![U43fa729e7b00456db29859f7ca1dff3dl](https://user-images.githubusercontent.com/33411707/143581366-a741ddb7-3aa6-42a2-92b1-b9aebce1b1de.png)
！！

也是新建DNS过滤器吗？谢谢！！

**Comment by hacamer** [comment]
是的，你也可以放进内容过滤器
