### ISSUE TITLE
误杀淘宝图片

### ISSUE THREAD

**Issue by dunkeng** [Cats-Team/AdRules#15]
https://s.taobao.com/search?q=%E8%BD%AF%E8%B7%AF%E7%94%B1&imgfile=&commend=all&ssid=s5-e&search_type=item&sourceId=tb.index&spm=a21bo.jianhua.201856-taobao-item.1&ie=utf8&initiative_id=tbindexz_20170306
![image](https://user-images.githubusercontent.com/22165870/148490019-db83db85-3754-4b16-bc07-b3933163d813.png)
https://vediotalk.taobao.com/category-1402800516.htm?spm=2013.1.w5002-18925975984.4.1ffa537ejnLkIp&search=y&catName=%C8%ED%C2%B7%D3%C9%D5%FB%BB%FA
![image](https://user-images.githubusercontent.com/22165870/148490054-513b2487-d34f-4b4f-a3c0-22a48f99d0b3.png)

通过ublock origin订阅了，两个规则
AdRules (For AdBlock)，这个规则影响
Allowlist，这个白名单应不应该订阅？还是要复制内容到白名单那一项里面？不太会用

**Comment by hacamer** [comment]
已尝试放行淘宝图片
