### ISSUE TITLE
bilibili播放会崩溃

### ISSUE THREAD

**Issue by bruce322** [Cats-Team/AdRules#161]
### Which tool do you use?

Other

### Other

qx

### Which AdRules DNS List Syntax do you use?

Quantumult X

### Which domain(s) should be unblocked?

bilibili

### Why should the domain(s) be unblocked?

播放视频直接崩溃

**Comment by DoingDog** [comment]
请发一下Bilibili崩溃时的QX日志，还有QX配置的[general]段内容

**Comment by DoingDog** [comment]
请问是否开启了`Rewrite`重写功能？Bilibili是否被代理？

**Comment by bruce322** [comment]
今天重现不了，可能是qx的问题
