### ISSUE TITLE
B站直播网页全屏无法收起侧边栏

### ISSUE THREAD

**Issue by longyuan1996** [Cats-Team/AdRules#17]
网页全屏时，”收起侧边栏“的按钮消失

正常情况：
![image](https://user-images.githubusercontent.com/15907278/151649910-256fcd7c-466d-4b90-84a1-e96fd82ff339.png)

异常情况：
![image](https://user-images.githubusercontent.com/15907278/151649930-1bb02c43-4667-4e17-bb27-47d5b01fb59d.png)

使用情况：Adguard订阅AdRules (For AdBlock)，同时安装Allowlist也不能解决

**Comment by hacamer** [comment]
未能发现此问题，请仔细检查
![5d846819f129db84](https://user-images.githubusercontent.com/73057402/151661212-56167f84-f81d-4108-8b7a-4ba35ad398c7.jpg)

**Comment by longyuan1996** [comment]
我这边的情况：
1. 开/关规则后，需要刷新两次才能复现
2. 打开规则后，对应的div会多出来一个样式
![image](https://user-images.githubusercontent.com/15907278/151669163-f1fc9e08-3984-4dcd-8e73-f0971f304055.png)
这个样式导致按钮的display从block变成none
![image](https://user-images.githubusercontent.com/15907278/151669111-7171e90c-f957-402b-bc52-23b816f9d771.png)

**Comment by longyuan1996** [comment]
找到有问题的规则了：
![image](https://user-images.githubusercontent.com/15907278/151669312-0e4dfbf5-fa19-40bc-ac67-fd0a89fc432b.png)
把这个规则关了就可以正常使用

**Comment by hacamer** [comment]
> 找到有问题的规则了： ![image](https://user-images.githubusercontent.com/15907278/151669312-0e4dfbf5-fa19-40bc-ac67-fd0a89fc432b.png) 把这个规则关了就可以正常使用

已经移除此条规则
