### ISSUE TITLE
microsoft edge 的起始页无法正常使用

### ISSUE THREAD

**Issue by suduogou** [Cats-Team/AdRules#197]
### Which tool do you use?

AdGuard Home

### Which AdRules DNS List Syntax do you use?

ABP

### Which domain(s) should be unblocked?

||ntp.msn.cn^
||ntp.msn.com^

### Why should the domain(s) be unblocked?

edge的起始页无法正常使用

**Comment by zutzo** [comment]
具体截图? 我这边无法复现

**Comment by suduogou** [comment]
> 具体截图?我这边无法复现

![003](https://github.com/user-attachments/assets/f138b70c-41aa-4089-b17c-aa3bcef5b5a8)
![002](https://github.com/user-attachments/assets/99072dcb-11a7-4102-b329-8cb3b929726a)
手动旅行后，恢复正常
![004](https://github.com/user-attachments/assets/adc259bf-7b10-48a3-b925-60324e0004d8)

**Comment by zutzo** [comment]
右上角选择是否相同
![图片](https://github.com/user-attachments/assets/bc2dd4c4-cd10-4734-a064-4fff0fc3ab8d)
我这边是 
![图片](https://github.com/user-attachments/assets/3f835ed6-0e81-409f-9848-5909a59306a0)
![图片](https://github.com/user-attachments/assets/e4838a82-7a60-4bb0-92ef-c01893ffb803)

两个是不同的

无法确定是否误杀

**Comment by suduogou** [comment]
被拦截了就是你第一张图那样
手动放行后，正常的是这样
![006](https://github.com/user-attachments/assets/385ff40b-15dc-4b91-9e59-21d5ef203a9d)

**Comment by zutzo** [comment]
了解了
