### ISSUE TITLE
skype wrongly block by rule "||events.data.microsoft.com^"

### ISSUE THREAD

**Issue by pekkle-hksar** [Cats-Team/AdRules#199]
### Which tool do you use?

AdGuard Home

### Which AdRules DNS List Syntax do you use?

ABP

### Which domain(s) should be unblocked?

events.data.microsoft.com

### Why should the domain(s) be unblocked?

refer to https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide
`events.data.microsoft.com` is required, but it is blocked and causing skype failed to connect

**Comment by zutzo** [comment]
can u upload any screenshot for skype ?

**Comment by pekkle-hksar** [comment]
![Screenshot_2024-08-30-16-18-59-036_com skype insiders-edit](https://github.com/user-attachments/assets/e32fd722-d4e3-4908-ae11-9a99a69101bf)

skype can continue to receive new messages but can't reply anything. 
I have added custom whitelist `@@||events.data.microsoft.com^`
and it works again.
