### ISSUE TITLE
误杀Apple Music

### ISSUE THREAD

**Issue by SongzhouYang** [Cats-Team/AdRules#20]
DNS规则里面 `||aod-` 误杀 `aod.itunes.apple.com`，
尽管规则放行了`aod.itunes.apple.com`的CNAME域名`aod.itunes.g.aaplimg.com`，
但仍然会导致直接访问`aod.itunes.apple.com`的请求被拒，导致Apple Music歌曲无法播放。

**Comment by hacamer** [comment]
已对该域名做放行处理，如有问题可重新打开该issue
