### ISSUE TITLE
成都高新减灾所的《地震预警》（com.huania.earthquakewarning）APP一直无法获取定位

### ISSUE THREAD

**Issue by hzy132** [Cats-Team/AdRules#200]
### Which tool do you use?

AdGuard Home

### Which AdRules DNS List Syntax do you use?

ABP

### Which domain(s) should be unblocked?

loc.map.baidu.com

### Why should the domain(s) be unblocked?

开启广告过滤后，成都高新减灾所的《地震预警》（com.huania.earthquakewarning）APP一直无法获取定位，会一直进行定位试图获取位置，造成大量的电量消耗，尝试放行loc.map.baidu.com后app就可正常获取定位，建议去除loc.map.baidu.com 。

**Comment by zutzo** [comment]
日志pls

**Comment by zutzo** [comment]
> ![Screenshot_20240906_110859](https://private-user-images.githubusercontent.com/35918116/365021304-ad4b0666-75cd-4ea1-8f13-cf4958f1b04e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTYxNTUsIm5iZiI6MTcyNTU5NTg1NSwicGF0aCI6Ii8zNTkxODExNi8zNjUwMjEzMDQtYWQ0YjA2NjYtNzVjZC00ZWExLThmMTMtY2Y0OTU4ZjFiMDRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA0MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YjE2OTdmYTFiNjQ5ZmUxYzI3M2YwNWQwNGRlZGVkYzdmODM1Nzk1ZTA3MDJlODY4OTYyNjA3OTUzYTdlMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ExQJgfwdG_QyKphuMdedwrrswSNGhaVDDwdwAabSofQ)

复制一下出来
