### ISSUE TITLE
Kuenstlermaerkte.de blocked

### ISSUE THREAD

**Issue by yoshimo** [Cats-Team/AdRules#203]
### Which tool do you use?

Other

### Other

Pihole

### Which AdRules DNS List Syntax do you use?

ABP

### Which domain(s) should be unblocked?

  ||jimdo.com^
web.jimdo.com

### Why should the domain(s) be unblocked?

It hosts non malicious content like https://www.kuenstlermaerkte.de/

**Comment by zutzo** [comment]
can u send any screenshots and logs?

**Comment by yoshimo** [comment]
```
2024-09-23 12:49:54 	A	www.kuenstlermaerkte.de
(blocked web.jimdo.com)
Blocked (gravity, CNAME)	CNAME (39.0ms)
```
