### ISSUE TITLE
腾讯视频网站移动端被误拦截

### ISSUE THREAD

**Issue by acxcdz** [Cats-Team/AdRules#207]
### Which tool do you use?

uBlock Origin

### Which List do you use?

AdRules AdBlock List Normal

### Which content should be unblocked?

该把m.v.qq.com##.open-app规则给去掉，因为它误拦截了有用的信息内容

### Why should the content be unblocked? Please Upload blocked log and screenshots!

m.v.qq.com##.open-app规则误拦截了https://m.v.qq.com/x/m/play?cid=mzc00200tfyde3m&vid=a4100rzgwx8网站视频播放页面有用的信息，
![IMG_20241123_112838](https://github.com/user-attachments/assets/3ee09fc9-3893-4d2d-886e-f8cc057241c2)
![Screenshot_20241123_113016](https://github.com/user-attachments/assets/fcb25956-a1f8-4039-b6c3-e91de24cedbb)
两张图片分别是被误拦截以后的截图，另一个则是没有被误拦截的截图

**Comment by CallMeR** [comment]
还有个这个域名 `mmstat.com`
被拦截后优酷会直接无法播放。
