### ISSUE TITLE
iOS 360手机卫士 safari网站安全检测扩展误杀

### ISSUE THREAD

**Issue by Gitguygogogo** [Cats-Team/AdRules#212]
### Which tool do you use?

Quantumult X

### Which AdRules DNS List Syntax do you use?

Quantumult X

### Which domain(s) should be unblocked?

可能是host-suffix,360protected.com,reject🤔

### Why should the domain(s) be unblocked?

![IMG_7641](https://github.com/user-attachments/assets/896e58a5-00bf-4592-bf99-cbf3472cb716)
qx中打开adrules规则即导致扩展的网址安全检测功能失效，关闭后即可正常使用检测功能。

**Comment by zutzo** [comment]
easylist 干的 
https://easylist.to/easylist/easylist.txt
https://github.com/easylist/easylist/issues/
