### ISSUE TITLE
请勿拦截feedback.miui.com

### ISSUE THREAD

**Issue by Carlos920** [Cats-Team/AdRules#27]
`feedback.miui.com`用于日志反馈，拦截后无法给官方反馈系统bug，请勿拦截此域名
![image](https://user-images.githubusercontent.com/32257015/165077032-48c98ab3-b30c-47c7-8681-ec6d85552613.png)

**Comment by hacamer** [comment]
已放行
https://github.com/Cats-Team/AdRules/blob/67761c61100a1059b79404710bef056cbe44ed21/mod/rules/dns-rules.txt#L1
