### ISSUE TITLE
虎牙加载缓慢 杀的太多了

### ISSUE THREAD

**Issue by aruisi888** [Cats-Team/AdRules#29]
虎牙加载缓慢 杀的太多了

**Comment by hacamer** [comment]
請告知是哪個部分加載慢
我這裏測試視頻加載正常
![image](https://user-images.githubusercontent.com/73057402/165293579-0844315b-323c-4635-97c2-ecab29bf27ea.png)
網頁加載稍慢

**Comment by aruisi888** [comment]
查了后台禁用项 有部分带P2P的域名杀掉后会加载缓慢 启用正常 但还有部分加载缓慢 不知道是不是我线路问题 比如像这个样的视频 加载会比较缓慢
 https://www.huya.com/cxldb
https://www.huya.com/11336726

**Comment by aruisi888** [comment]
al.p2p.huya.com 这个禁用的放行可以了

**Comment by hacamer** [comment]
> 查了后台禁用项 有部分带P2P的域名杀掉后会加载缓慢 启用正常 但还有部分加载缓慢 不知道是不是我线路问题 比如像这个样的视频 加载会比较缓慢 https://www.huya.com/cxldb https://www.huya.com/11336726

我測試過，安卓，網頁似乎都沒有這個問題
依舊能以較快的速度加載

**Comment by hacamer** [comment]
现在怎么样了？😊

**Comment by aruisi888** [comment]
虎牙有的视频还是会卡顿 有的要换线路才行 放行下列
@@||al.p2p.huya.com^$important
@@||bd.p2p.huya.com^$important
@@||hw.p2p.huya.com^$important
@@||livewebbs2.msstatic.com^$important

另外百度首页推荐的视频打不开

https://mbd.baidu.com/newspage/data/videolanding?nid=sv_16567120251419387164&sourceFrom=pc_feedlist

放行@@||mbdp02.bdstatic.com^$important

**Comment by aruisi888** [comment]
阿里旺旺 AliIM_taobao_(9.12.12C) (1) 这个版本和对面聊天点击网页卖家头像弹不出聊天窗口  这个放行 @@||
amos.alicdn.com^$important

杏梢 ***@***.***> 于2022年5月17日周二 23:24写道：
