### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by limguofeng** [Cats-Team/AdRules#3]
https://yandex.com/images/touch/search?rpt=imageview&redircnt=1621069570.1&ncrnd=3502
![Screenshot_2021-08-31-19-28-59-433_com.kiwibrowser.browser.jpg](https://user-images.githubusercontent.com/79099696/131494999-432bf8e7-6322-481c-b9fa-5e0904e5176b.jpg)
在yandex搜图后，会把原图片给拦截

**Comment by Potterli20** [comment]
我修了，你看作者有没有上游我的白名单就知道了

**Comment by hacamer** [comment]
请尝试使用白名单

**Comment by Potterli20** [comment]
已加入白名单
