### ISSUE TITLE
[误杀] 用 AdRules (For AdBlock) 的话，https://www.mydrivers.com/ 这个网站很多页面有一些链接的都会被拦截。

### ISSUE THREAD

**Issue by flyhong666** [Cats-Team/AdRules#33]
如：https://news.mydrivers.com/1/829/829387.htm 还有很多都是这样的情况。

**Comment by hacamer** [comment]
没毛病你的意思，能截个图吗？

**Comment by flyhong666** [comment]
![image](https://user-images.githubusercontent.com/76857714/166408275-7a62cce4-3eed-4c10-9044-f83849939b94.png)
启用AdRules (For AdBlock) 规则，红色标的链接就没了。

**Comment by flyhong666** [comment]
![image](https://user-images.githubusercontent.com/76857714/166408443-ffcfe12b-3434-433b-b6b4-43e72162ca21.png)

**Comment by hacamer** [comment]
```
@@||mydrivers.com^$stealth
@@||dt.mydrivers.com^$domain=news.mydrivers.com
```
你试试这两条规则行不行

**Comment by flyhong666** [comment]
adblock plus 没法搞这个进去哦。

**Comment by hacamer** [comment]
在我关闭了AdGuard后好像也不行🙃

**Comment by flyhong666** [comment]
就用到我说你的这个规则才会，默认的不会哦。

**Comment by hacamer** [comment]
奇奇怪怪的bug🧐

**Comment by hacamer** [comment]
我使用 `ublock Origin` 似乎没有这个问题，但是用 `AdBlock Plus` 和 `AdGuard` 却链接显示不出来

**Comment by flyhong666** [comment]
> 我使用 `ublock Origin` 似乎没有这个问题，但是用 `AdBlock Plus` 和 `AdGuard` 却链接显示不出来

我也ublock 也会。。。

**Comment by hacamer** [comment]
已修复
