### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by SakuraFallingMad** [Cats-Team/AdRules#34]
域名：share.dmhy.org（非常重要，没有域名基本无法排查误杀，提交了也很大概率无法解决你的问题）
发生时间：2022年05月01日
使用的列表： AdRules (For DNS)  不排除其他列表也包括此
使用的工具：AdGuard Home
问题描述：![image](https://user-images.githubusercontent.com/31793080/166851217-3da59f43-cf05-4127-9ae8-ab736b299624.png)

**Comment by hacamer** [comment]
这个域名是干什么的，能说一下吗？

**Comment by SakuraFallingMad** [comment]
动漫花园的BT下载站，非常古老了
