### ISSUE TITLE
奇异果tv不能过滤了，

### ISSUE THREAD

**Issue by nb12nb34** [Cats-Team/AdRules#35]
奇异果tv不能过滤了，大佬能看看能修复规则不

**Comment by hacamer** [comment]
现在怎么样了？😊

**Comment by nb12nb34** [comment]
测试了，一直都不行，现在添加了其他第三方规则，暂时解决了。。不知道是不是我编译的版本问题

**Comment by hacamer** [comment]
> 测试了，一直都不行，现在添加了其他第三方规则，暂时解决了。。不知道是不是我编译的版本问题

具体是啥规则，能说一下吗

**Comment by nb12nb34** [comment]
https://gitee.com/halflife/list/raw/master/ad.txt

**Comment by hacamer** [comment]
优化了DNS规则的白名单，你可以试试问题解决了没有

**Comment by nb12nb34** [comment]
现在已经可以了，非常感谢！

**Comment by hacamer** [comment]
OK
