### ISSUE TITLE
[误杀]apple news

### ISSUE THREAD

**Issue by Pollo3470** [Cats-Team/AdRules#36]
域名：news-events.apple.com
使用的列表： AdRules (For DNS)
使用的工具：AdGuard Home
该域名的作用：apple news相关

**Comment by Pollo3470** [comment]
![image](https://user-images.githubusercontent.com/90445326/167791313-7b88ce1a-ab3b-4e24-a39c-da985824c8d1.png)
我在规则里没有看到拦截这个域名的条目，但是拦截记录里有

**Comment by hacamer** [comment]
正则问题，稍后更新下规则
