### ISSUE TITLE
[误杀] 微软相关被误杀

### ISSUE THREAD

**Issue by Carlos920** [Cats-Team/AdRules#43]
域名：
code.visualstudio.com 
dc.services.visualstudio.com
update.code.visualstudio.com

使用的列表： AdRules DNS List
使用的工具：AdGuard Home
问题描述：
vscode 官网、以及vscoden内置更新被误拦截

该域名的作用：
![image](https://user-images.githubusercontent.com/32257015/174314640-3255c1b9-1905-427a-a9c5-ce3f9fce0534.png)
![image](https://user-images.githubusercontent.com/32257015/174314673-5b80e665-2054-45d8-920d-821bf5b3bca0.png)

**Comment by hacamer** [comment]
能否提供下问号处的日志
![image](https://user-images.githubusercontent.com/73057402/174321594-c7669646-8b06-4165-87bf-4bc5e2d7ed8c.png)
应该是CNAME被拦截了

**Comment by hacamer** [comment]
已修复
