### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by jiayouba233** [Cats-Team/AdRules#44]
域名：
stats.foldingathome.org 

使用的列表： CHN: AdRules DNS List
使用的工具：AdGuard DNS(Beta)
问题描述：
![图片](https://user-images.githubusercontent.com/72449367/174420678-b66b26f4-14b1-4128-b11d-1c2f23c4fbcc.png)

该域名的作用：Folding@Home 的用户运算统计页面

**Comment by hacamer** [comment]
修好了，等一个小时后AdGuardDNS那边才会同步到
