### ISSUE TITLE
使用代理软件，该引用哪个规则？

### ISSUE THREAD

**Issue by 5points** [Cats-Team/AdRules#45]
之前有`surge.txt`的时候。我只需要简单做个格式转换就能用在QuanX上。
这次想更新的时候，却发现`surge.txt`已经删除了。
如果可以请问能把`surge.txt`添加回来吗？

**Comment by hacamer** [comment]
不好意思哈，昨天更新脚本的时候弄掉了😂话说qx是哪种格式的规则？我适配一下

**Comment by 5points** [comment]
辛苦你了！特意要你适配！一般格式如下，` reject `参数只是我个人习惯，可以不用加。
` host-suffix,example.com,reject `
` host,example.com,reject `
` ip-cidr,1.2.3.4/32,reject `

**Comment by hacamer** [comment]
> 辛苦你了！特意要你适配！一般格式如下，`reject`参数只是我个人习惯，可以不用加。 `host-suffix,example.com,reject` `host,example.com,reject` `ip-cidr,1.2.3.4/32,reject`

https://github.com/Cats-Team/AdRules/blob/main/qx.conf
弄出来了，你看看能不能用，能用的话我就优化一下

**Comment by hacamer** [comment]
> > 辛苦你了！特意要你适配！一般格式如下，`reject`参数只是我个人习惯，可以不用加。 `host-suffix,example.com,reject` `host,example.com,reject` `ip-cidr,1.2.3.4/32,reject`
> 
> https://github.com/Cats-Team/AdRules/blob/main/qx.conf 弄出来了，你看看能不能用，能用的话我就优化一下

还在调试

**Comment by hacamer** [comment]
已经可以正常使用了，
链接 ：https://raw.githubusercontent.com/Cats-Team/AdRules/main/qx.conf



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2022年6月20日(週一) 中午12:35
收件人： ***@***.***&gt;;
抄送： ***@***.******@***.***&gt;;
主旨： Re: [Cats-Team/AdRules] 使用代理软件，该引用哪个规则？ (Issue #45)




 
辛苦你了！特意要你适配！一般格式如下，reject参数只是我个人习惯，可以不用加。
 host-suffix,example.com,reject
 host,example.com,reject
 ip-cidr,1.2.3.4/32,reject

**Comment by 5points** [comment]
上午导入的时候出错了，但是现在导入已经没有问题了！谢谢你！

> 已经可以正常使用了， 链接 ：https://raw.githubusercontent.com/Cats-Team/AdRules/main/qx.conf
