### ISSUE TITLE
[误杀]b站无法加载评论区

### ISSUE THREAD

**Issue by simpread** [Cats-Team/AdRules#47]
个人认为是clearURL导致的，使用ClearURLs for uBo (https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt) 会导致同样情况。

使用的列表： AdRules AdBlock List 通用规则
使用的工具：ublock origin
问题描述：![图片](https://user-images.githubusercontent.com/81662464/175757698-0c2bd2a4-3fcf-41dd-8818-774c3cf4ae49.png)

**Comment by hacamer** [comment]
我测试了，似乎并没有复现你这个问题 
可能是我安卓的原因，我找其他人试试

**Comment by simpread** [comment]
> 我测试了，似乎并没有复现你这个问题 可能是我安卓的原因，我找其他人试试

可能吧，我用的火狐+chrome(PC)

**Comment by hacamer** [comment]
> > 我测试了，似乎并没有复现你这个问题 可能是我安卓的原因，我找其他人试试
> 
> 可能吧，我用的火狐+chrome(PC)

找别人看了下，别人Chrome（PC）+ ublock origan也没问题

**Comment by simpread** [comment]
> > > 我测试了，似乎并没有复现你这个问题 可能是我安卓的原因，我找其他人试试
> > 
> > 
> > 可能吧，我用的火狐+chrome(PC)
> 
> 找别人看了下，别人Chrome（PC）+ ublock origan也没问题

好的谢谢了，可能是我这边的问题
