### ISSUE TITLE
更新规则被限速

### ISSUE THREAD

**Issue by mpamxl** [Cats-Team/AdRules#48]
RT，在Via或者X浏览器上，最近国内Coding源的AdRules AdGuard Filter List开始更新规则会被限速，需要等很久才会更新完成，之前不会，都是很快，并且其它Coding规则都很正常，请求修复。

**Comment by hacamer** [comment]
> RT，在Via或者X浏览器上，最近国内Coding源的AdRules AdGuard Filter List开始更新规则会被限速，需要等很久才会更新完成，之前不会，都是很快，并且其它Coding规则都很正常，请求修复。

这个问题应该找coding，我们暂不清楚是什么原因

**Comment by mpamxl** [comment]
可是很奇怪的是其他的Coding规则就不会这样，我开始也以为Coding的原因，但是测试了其他Coding规则好像并不会这样等很久才更新完成，但是电脑打开规则好像也正常，并且这个问题从前几天才开始，所以以为是设置了限速，可否请测试下，看能否有办法解决呢？

**Comment by hacamer** [comment]
> 可是很奇怪的是其他的Coding规则就不会这样，我开始也以为Coding的原因，但是测试了其他Coding规则好像并不会这样等很久才更新完成，但是电脑打开规则好像也正常，并且这个问题从前几天才开始，所以以为是设置了限速，可否请测试下，看能否有办法解决呢？

已向coding提交工单，等待受理中

**Comment by mpamxl** [comment]
非常感谢，我怀疑这个规则文本下载4M+，会不会因为Coding超过4M现在有了限速或者什么别的原因？不管怎样问题确实存在，先等待答复吧，辛苦啦！

**Comment by hacamer** [comment]
得到了coding的回复了
![](https://user-images.githubusercontent.com/73057402/175784496-b5de9368-4d28-4f82-a187-2f0224bae98a.jpg)
看来还是得增加几个镜像链接

**Comment by hacamer** [comment]
https://github.com/Cats-Team/AdRules/commit/db5e58fbac4caa00dc1870434f86ba597a994328
已新增一个镜像

**Comment by mpamxl** [comment]
了解！非常感谢，国内源还是得有个稳定点的。现更换新的镜像目前正常了。

**Comment by mpamxl** [comment]
今天测试了下，新的镜像如果手机更新也会很慢，跟Coding差不多，有没有更好的选择呢？如果只有这两个的话就只有忍受下了

**Comment by hacamer** [comment]
> 今天测试了下，新的镜像如果手机更新也会很慢，跟Coding差不多，有没有更好的选择呢？如果只有这两个的话就只有忍受下了

今天搞了这个 https://adrules.onrender.com/ 不过貌似还是很慢
coding恐怕是没希望了，客服回答说会一直限制（所有用户）
~其实fsofso已经很快了，500kb/s总比coding的50kb/s快~

**Comment by mpamxl** [comment]
刚测试了下https://adrules.onrender.com/adguard.txt用VPN更新很快，但只要不用WIFI和VPN，确实还是很慢，没有办法弄像Coding之前那样很稳定的吗？

**Comment by mpamxl** [comment]
Gitee如何？会不会好点

**Comment by mpamxl** [comment]
目前我连上WIFI测试，Coding和FsoFso差不多，都比较慢，而 https://adrules.onrender.com/ 相对是最快的，至少连接WIFI下很快，但是断开WIFI不用VPN的话还是达不到之前Coding的几秒就更新完。

**Comment by hacamer** [comment]
> Gitee如何？会不会好点

不会，1m文件需要登陆，还要实名验证

**Comment by hacamer** [comment]
https://raw.iqiq.io/Cats-Team/AdRules/main/adblock.txt

https://cdn.staticaly.com/gh/Cats-Team/AdRules/main/adblock.txt

https://raw.fastgit.org/Cats-Team/AdRules/main/adblock.txt

https://gcore.jsdelivr.net/gh/Cats-Team/AdRules@main/adblock.txt

这几个链接你都可以试试，看看哪个快

**Comment by mpamxl** [comment]
raw.iqiq.io和raw.fastgit.org好像可以，其他两个差点，而且更新也不如这个及时

**Comment by hacamer** [comment]
> raw.iqiq.io和raw.fastgit.org好像可以，其他两个差点，而且更新也不如这个及时

这两个是实时的，服务器好像都在香港
不过IQio那个不稳定 fast也是 偶然的

**Comment by hacamer** [comment]
https://adrules.netlify.app

https://adrules.netlify.app/adblock.txt

刚刚又弄了一个，我这里速度不错，你可以试试

**Comment by mpamxl** [comment]
刚测试了下IQio比 https://adrules.netlify.app 快一些，其实快是一方面，另一方面能稳定最好啦

**Comment by hacamer** [comment]
感觉国外的托管计划玩不起，基本上是100GB一个月，被人刷刷就没了😂现在少说也有几千人用，一个月下来几个TB都有可能 
流量真的玩不起😂

**Comment by hacamer** [comment]
https://cats-team.github.io/AdRules/adblock.txt

https://cats-team.github.io/AdRules/
github pages服务好像也行，你看看，我这里更新速度与以前的coding差不多快

**Comment by hacamer** [comment]
还有adblock_plus.txt啊
10MB的规则
coding限速了 AdGuard直接加载错误

**Comment by mpamxl** [comment]
所以还是得发掘下国内源比较快速稳定的，Coding这次搞得一下就有点尴尬了，国外源github就行我觉得，目前反正我用IQio好像最快速稳定，即使不连WIFI和VPN也是很快刷新。

**Comment by hacamer** [comment]
> 所以还是得发掘下国内源比较快速稳定的，Coding这次搞得一下就有点尴尬了，国外源github就行我觉得，目前反正我用IQio好像最快速稳定，即使不连WIFI和VPN也是很快刷新。

国内源几乎都没了，国外源挺多。
IQ的，，唉 还是用户自己选择吧，毕竟偶然会炸几次，有时候长达炸一个月

**Comment by hacamer** [comment]
> 这...Fastgit好像也还行，那相对来说比较稳定快速的是哪个呢？

那,,,就fastgit吧

**Comment by hacamer** [comment]
> 也真是醉了，Coding客服那边说以后都没可能恢复了吗？

对

**Comment by hacamer** [comment]
![microsof](https://user-images.githubusercontent.com/73057402/176213032-67fc3861-c15c-4eea-9a4d-5da75ab29c5f.jpg)

**Comment by mpamxl** [comment]
经测试还是IQ最好用，Fastgit随时不行

**Comment by hacamer** [comment]
> 经测试还是IQ最好用，Fastgit随时不行

自行选择，合适就好
