### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by 5points** [Cats-Team/AdRules#49]
域名：
epochtimes.com|org

使用的列表： qx.conf
使用的工具：quantumultX
问题描述：![image](https://user-images.githubusercontent.com/8995110/176216640-b702d33c-d218-4cf9-9580-f7cfa3a7dc23.png)

该域名的作用：

**Comment by hacamer** [comment]
这个域名的作用是？

**Comment by 5points** [comment]
就是打开的时候，发现没法访问。其实并不是广告。属于“不太好说“的网站

**Comment by hacamer** [comment]
fix

**Comment by hacamer** [comment]
修好了
