### ISSUE TITLE
[误杀]Bilibili个人空间显示有问题

### ISSUE THREAD

**Issue by yinzhiyizhi** [Cats-Team/AdRules#51]
域名：
https://space.bilibili.com/448340479 

使用的列表： AdRules AdBlock List Full  
使用的工具：ublock origin 
问题描述：打开的时候加载较慢，另外还会出现错误提示，提示获取用户专栏列表失败，网络错误 。页面会没有右手边个人介绍充电计划等的那一栏 

该域名的作用：

**Comment by yinzhiyizhi** [comment]
另外关注无法点击，置顶视频推荐被误杀了
https://space.bilibili.com/1833524110

**Comment by hacamer** [comment]
测试环境：
软件AdGuard 3.6.8
插件ublock origan 1.43.0
浏览器Kiwi Browser 101.0.4951.0
桌面版模式
暂未发现这两个问题

**Comment by yinzhiyizhi** [comment]
环境：
使用的列表： AdRules AdBlock List Full
插件ublock origan 1.43.0
浏览器Brave Browser [版本 1.40.107 Chromium: 103.0.5060.53（正式版本） （64 位）](https://brave.com/latest/)
桌面版模式

我关了订阅列表就没有这两个问题，打开之后刷新就有了，关了之后刷新就出现缺失部分

**Comment by hacamer** [comment]
试试在自定义规则添加此条
`@@||api.bilibili.com/*$removeparam`

**Comment by yinzhiyizhi** [comment]
在自定义静态规则添加以下规则，出现的问题没有了
@@||api.bilibili.com/*$removeparam

**Comment by yinzhiyizhi** [comment]
`@@||api.bilibili.com/*$removeparam`

**Comment by hacamer** [comment]
> 

那可以判定就是API被Removeparam了
稍后修复
