### ISSUE TITLE
[误杀] 网易云搜索被拦截

### ISSUE THREAD

**Issue by Carlos920** [Cats-Team/AdRules#53]
域名/误拦截的东西：网易云搜索
使用的列表：  AdRules DNS List
使用的工具： AdGuard
问题描述：

误杀的规则(可选):
iadmusicmat.music.126.net

被拦截方式：
- [ ] 单域名拦截
- [ ] CNAME拦截

**Comment by hacamer** [comment]
请补全一下信息
