### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by SakuraFallingMad** [Cats-Team/AdRules#55]
域名/误拦截的东西：abema.tv
使用的列表： AdRules DNS List
使用的工具：Adguard Home
问题描述：![image](https://user-images.githubusercontent.com/31793080/178219161-8c035e5d-2891-4cf7-8223-3202c92198c3.png)

误杀的规则(可选):

||ab

这规则误杀有点吓人了

**Comment by hacamer** [comment]
emmm这个，，，你更新规则试试？
或许是没有下载完整

**Comment by SakuraFallingMad** [comment]
好 我试试看 应该是有问题的 如何真是这样规则 简直是地图炮

杏梢 ***@***.***> 于 2022年7月12日周二 上午10:26写道：

**Comment by hacamer** [comment]
毕竟有时候adgh没有完全下载规则
造成奇奇怪怪的误杀

**Comment by hacamer** [comment]
怎么样了？

**Comment by SakuraFallingMad** [comment]
没问题了 应该是adg的问题 哎 麻烦你了

杏梢 ***@***.***> 于 2022年7月13日周三 上午10:36写道：

**Comment by hacamer** [comment]
没事没事
