### ISSUE TITLE
[误杀] 招商银行掌上生活无法联网

### ISSUE THREAD

**Issue by FanxJK** [Cats-Team/AdRules#57]
域名/误拦截的东西：招商银行掌上生活无法联网
使用的列表： DNS拦截列表：`AdRules DNS List` , DNS 允许列表: `AdRules Allowlist`
使用的工具：`AdGuard Home`
问题描述：
打开招商银行掌上生活提示网络异常，并无法登录与加载APP相关内容
将: `metric.ccc.cmbchina.com` 加白后正常

相关反馈：https://www.right.com.cn/forum/forum.php?mod=redirect&goto=findpost&ptid=6207755&pid=17027385 332楼
错误原因：
`metric.ccc.cmbchina.com` 匹配到 `https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt` 的
```
/((^)|(.))metric./
```
并且 `AdRules Allowlist`  未存在 `metric.ccc.cmbchina.com` 相关规则, 导致规则被匹配

**Comment by hacamer** [comment]
非常抱歉，现在才看到这个问题，现在已经修好了，待会更新规则就行

**Comment by hacamer** [comment]
这个域名之前加白过，可能是之前迁移脚本的时候丢失了，非常抱歉
感谢你的详细反馈❤
