### ISSUE TITLE
[误杀] Paypal 网页页面加载不全

### ISSUE THREAD

**Issue by FanxJK** [Cats-Team/AdRules#58]
域名/误拦截的东西：Paypal 页面加载不全
使用的列表： DNS拦截列表：AdRules DNS List , DNS 允许列表: AdRules Allowlist
使用的工具：AdGuard Home
问题描述：
Paypal 网页页面加载不全
将: `www.paypalobjects.com` 加白后正常

相关：https://www.hostloc.me/forum.php?mod=viewthread&tid=817687
错误原因：
`www.paypalobjects.com` 匹配到 `https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt` 的
```
||paypalobjects.com^
```

**Comment by hacamer** [comment]
感谢反馈，稍后更新就好
