### ISSUE TITLE
[误杀]百度网盘的一些显示内容

### ISSUE THREAD

**Issue by yinzhiyizhi** [Cats-Team/AdRules#59]
域名/误拦截的东西：
使用的列表：AdRules AdBlock List Full 
使用的工具：ublock origin
问题描述：https://pan.baidu.com/ 
				  误杀了百度网盘用户名右边的SVIP等级显示和转存其他人分享的文件夹显示的转存文件数超过上限的提示

误杀的规则(可选):

被拦截方式：
- [ ] 单域名拦截
- [ ] CNAME拦截

**Comment by hacamer** [comment]
有无截图？

**Comment by yinzhiyizhi** [comment]
![image](https://user-images.githubusercontent.com/10783956/179430674-6c7f5952-81a3-4a66-aea9-bd57fd7782d6.png)

![image](https://user-images.githubusercontent.com/10783956/179430580-36150eea-c34c-407b-968c-3726a972e3b6.png)

就是这两个

**Comment by hacamer** [comment]
没有VIP无法复现你的问题
但你可以试试在用户过滤器添加这条规则
`@@||baidu.com$generichide`

**Comment by yinzhiyizhi** [comment]
不好意思，我才发现VIP哪个图标被屏蔽是另外一个订阅规则引起的，不是你的规则的问题。
我关了其它的规则留下你的规则刷新网页，保存其他人分享的文件夹，还是没有弹出保存文件数超过限制的提示，关了你的规则刷新网页之后再试就显示。而且连转存时候的提示都没有，转存时候会有提示，提示你正在转存中，进度是多少百分比。
![image](https://user-images.githubusercontent.com/10783956/179645303-abf07455-07f6-48df-ba1f-3a775b16a786.png)

**Comment by hacamer** [comment]
没网盘链接我也难排除😂 我还没遇到过

**Comment by yinzhiyizhi** [comment]
😂😂😂我那个文件夹要保密不能分享

**Comment by DoingDog** [comment]
尝试修复...
规则:

@@||pan.baidu.com^$removeparam=logid

**Comment by DoingDog** [comment]
请看看是否同时修复了转存超过限制的提示，我没有会员保存文件不出来这个提示

**Comment by yinzhiyizhi** [comment]
不对啊，这个提示应该是只要超过数量限制都会显示，不管有没有会员，只不过是会员的数量限制上限更高而已。
还是没有提示超过数量限制。

**Comment by DoingDog** [comment]
> 不对啊，这个提示应该是只要超过数量限制都会显示，不管有没有会员，只不过是会员的数量限制上限更高而已。 还是没有提示超过数量限制。

转存进度是否修复？

**Comment by DoingDog** [comment]
![image](https://user-images.githubusercontent.com/72430078/184479165-ffe6728d-8275-487b-981c-e3a3920ec297.png)

这是我看到的界面，没有红色的提示出现

**Comment by yinzhiyizhi** [comment]
![image](https://user-images.githubusercontent.com/10783956/184528290-4c4719fa-6e1e-4bc7-b773-511ebd5b5e6a.png)
我一开始尝试转存的时候没有显示进度，直接显示空间不足
我删了网盘内容再转存，没有显示进度，也没有显示转存超过限制

**Comment by DoingDog** [comment]
https://github.com/Cats-Team/AdRules/commit/60149cb6d33d425a70e43e0d82f888d7575463dd

更新规则试试

**Comment by hacamer** [comment]
[该issue由于长期无恢复，暂时关闭，如有需要再开启]
