### ISSUE TITLE
有一些疑问+请问是否有针对移动端Adguard的规则？

### ISSUE THREAD

**Issue by 5points** [Cats-Team/AdRules#62]
1.如果有针对ios或android的Adguard的规则，我该用哪个？
2.其次还有个问题，在openwrt的adguardhome上
是否选择带有adguard字眼的规则使用？
如：
**AdBlock Plus类规则**
`AdRules AdGuard Filter List 合并的AdGuard列表`
**超大规则**
`AdRules AdGuard Full List`
在**DNS类规则**中，应该挑哪个使用？
3.在白名单中，是否添加`AdRules Allowlist`允许名单也是可以生效的？

**Comment by hacamer** [comment]
1.默认的且建议使用列表是 `AdRules AdBlock List`
AdGuard 字眼的 都是只有AdGuard默认的所有过滤器
2.OP的AGH用 `AdRules DNS List`
3.是的，都生效 ~没啥事就不要用白名单~

~btw:怎么写的这么清楚的说明还是有人不懂啊aaaa，哭死😭~

**Comment by 5points** [comment]
哈哈哈，抱歉我是小白。
因为理解有问题，导致我看到很多名称就雨里雾里了。
经过你这么一说，就突然明白了！
非常感谢你的解答
