### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by Nanqian** [Cats-Team/AdRules#65]
域名/误拦截的东西：es6.ruanyifeng.com
使用的列表： AdRules AdBlock List, AdRules AdGuard Filter List
使用的工具：ublock origin
问题描述：
![image](https://user-images.githubusercontent.com/30768150/183844006-6825795d-af4f-442a-8a90-229e37bdc89e.png)
会有一瞬间出现内容然后又没了，再然后就是这个提示

误杀的规则(可选):

**Comment by Nanqian** [comment]
首页可以，具体的某一页就不行了，比如这个https://es6.ruanyifeng.com/#docs/module

**Comment by DoingDog** [comment]
ruanyifeng.com#@#a[href*=".apeclass.com"]
