### ISSUE TITLE
[误杀]B站视频无法投币和收藏，只能点赞

### ISSUE THREAD

**Issue by yinzhiyizhi** [Cats-Team/AdRules#66]
域名/误拦截的东西：Bilibili视频无法投币和收藏，只能点赞
使用的列表： AdRules AdBlock List Full   
使用的工具：ublock origin 
问题描述：B站视频无法投币和收藏，只能点赞，关闭该订阅规则后恢复正常

误杀的规则(可选):

被拦截方式：
- [ ] 单域名拦截
- [ ] CNAME拦截

**Comment by DoingDog** [comment]
bilibili.com#@#.bili-dialog-m
