### ISSUE TITLE
[误杀] 虎牙直播部分资源无法加载

### ISSUE THREAD

**Issue by FanxJK** [Cats-Team/AdRules#67]
域名/误拦截的东西：虎牙直播部分资源无法加载
使用的列表： DNS拦截列表：AdRules DNS List , DNS 允许列表: AdRules Allowlist
使用的工具：AdGuard Home
问题描述：
虎牙直播部分资源无法加载
将: `livewebbs2.msstatic.com` 加白后正常

错误原因：
`livewebbs2.msstatic.com` 匹配到 `https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt` 的
```
||liveweb*.msstatic.com^
```

截图:
<img width="1199" alt="huya" src="https://user-images.githubusercontent.com/22773968/185737109-e01eff29-f678-4605-9e5f-47134a1c3494.png">

**Comment by hacamer** [comment]
五个小时后规则会重新构建，五小时后更新后即可

**Comment by FanxJK** [comment]
问题又存在了，`livewebbs2.msstatic.com` 又被拦截了

**Comment by FanxJK** [comment]
> 五个小时后规则会重新构建，五小时后更新后即可

问题又存在了，`livewebbs2.msstatic.com` 又被拦截了
