### ISSUE TITLE
[误杀]哔哩哔哩、SM图床

### ISSUE THREAD

**Issue by zhihang-yi** [Cats-Team/AdRules#69]
域名/误拦截的东西
- 哔哩哔哩、SM图床

使用的列表
- AdRules DNS List

使用的工具
- AdGuard,

问题描述
- `dataflow.biliapi.com`
> 拦截该域名将导致哔哩哔哩视频初始加载异常缓慢
![](https://s2.loli.net/2022/09/01/MVUxhPmiXoR1vsF.jpg)
![](https://s2.loli.net/2022/09/01/iZnkI1hRGmrAfOK.jpg)
---
- `s2.loli.net`
> 此为公共图床SM图床的图片直链。如本`issue`中的两张截图均使用此图床。

误杀的规则
1. ||s2.loli.net^
2. ||dataflow.biliapi.com^

被拦截方式：
- ⚠️ CNAME拦截

**Comment by hacamer** [comment]
@zhihang-yi 很抱歉，由于学业繁忙 现在才得以回复您的问题

1. bilibili我测试了 没有发现问题
2. SM图床误杀问题已修复
