### ISSUE TITLE
[误杀]最近整理的部分误杀清单

### ISSUE THREAD

**Issue by liangfyx** [Cats-Team/AdRules#71]
# 小米安装apk时病毒查杀
api.installer.xiaomi.com
# QQ签到后每日图片
tianshu.gtimg.cn
# 支付宝企鹅共享扫吹风机时加载过慢放行域名
qiekj-web-log.cn-shanghai.log.aliyuncs.com
# 百度搜索的部分图片
events.baidu.com
# 启航教育无法播放视频放行域名
p.bokecc.com
errlog.umeng.com

**Comment by hacamer** [comment]
1.这个可能只会添加到白名单

2.暂时无法复现，之后再看

3.无法复现，且规则中没有这个域名

4.同上

5.同上

**Comment by liangfyx** [comment]
企鹅共享支付宝加载过慢误杀材料补充
![Uploading 1662799182576.jpg…](3、企鹅共享二维码，支付宝扫码)

**Comment by hacamer** [comment]
@liangfyx 重新看了 3  并无发现加载慢问题 请检查规则是否为最新

**Comment by liangfyx** [comment]
我手动添加我那个规则后速度很快，我手动去掉那个规则后支付宝扫码后会一直转圈要等好一会才行😂，要不我就手动添加下好了~

**Comment by hacamer** [comment]
> 我手动添加我那个规则后速度很快，我手动去掉那个规则后支付宝扫码后会一直转圈要等好一会才行😂，要不我就手动添加下好了~

@liangfyx 奇怪了 要不你截图下被拦截日志？

**Comment by liangfyx** [comment]
![image](https://user-images.githubusercontent.com/20663717/189484202-4cb5051a-da99-4812-87bd-f228c3b51ce1.png)
![8F897938326589061E6842E4F286B933](https://user-images.githubusercontent.com/20663717/189484220-b607faa9-6aa6-4335-a1b9-633df5cc7961.jpg)
在支付的时候回一直转圈好一会

**Comment by liangfyx** [comment]
好像是adguard自带的规则拦截了

**Comment by hacamer** [comment]
阿这😂
