### ISSUE TITLE
[误杀]腾讯视频网页、腾讯极光TV版本无法播放视频

### ISSUE THREAD

**Issue by sun3596209** [Cats-Team/AdRules#75]
域名/误拦截的东西：
使用的列表： 
使用的工具：
问题描述：](url)

误杀的规则(可选):

视频无法播放时，拦截了如下规则。关闭CHN: AdRules DNS List，清除DNS缓存，视频正常播放。

![99d668c50e6130d46f6060560a6f943](https://user-images.githubusercontent.com/3975993/190859361-6a2b62a0-b023-400d-a5a1-97f28f740b6c.jpg)

**Comment by hacamer** [comment]
@sun3596209 经过测试 并无问题 请再次检查

```
测试环境：
过滤工具：AdGuardHome 、AdGuard
过滤列表：adrules adblock list、adrules dns list
系统：Android 12L
APP：极光TV 最新版
网页端：Microsoft Edge dev 最新版

均无问题
```

**Comment by zdante** [comment]
> 
测试环境：openwrt
过滤环境：AdRules AdBlock List,adrules dns list,AdRules AdGuard Filter List,AdRules AdBlock List Full,AdRules Hosts List.
系统：macos
浏览器：Firefox  Safari

实测腾讯视频网站可访问，但是视频无法播放。关闭adrules dns list过滤规则则恢复。再次开启过滤规则等待缓存过期则视频无法播放。观察规则过滤记录后，将vd6.l.qq.com写入允许后，视频可以播放。

**Comment by hacamer** [comment]
![Screenshot_20220927-003759_Lawnchair](https://user-images.githubusercontent.com/73057402/192332957-d50a68ff-00d8-4db6-b4c6-ee1b6b9fda4d.png)
再次测试，依旧无法复现问题

**Comment by zdante** [comment]
> ![Screenshot_20220927-003759_Lawnchair](https://user-images.githubusercontent.com/73057402/192332957-d50a68ff-00d8-4db6-b4c6-ee1b6b9fda4d.png) 再次测试，依旧无法复现问题


今天再看了下，挺奇怪的，这个vd6.l.qq.com网址24号是会被拦截的，今天27号我把之前自己写的允许项删除后，发现这个网址已经不再被规则拦截了。vd6.l.qq.com网址不再被拦截，这也许是你无法复现的原因。
<img width="1066" alt="截屏2022-09-27 18 29 57" src="https://user-images.githubusercontent.com/39561185/192503156-bd9d80b9-5750-45c5-b118-9257e0f11ad3.png">
<img width="1031" alt="截屏2022-09-27 18 31 06" src="https://user-images.githubusercontent.com/39561185/192503212-a9660152-8499-46b3-9520-e06a252a3e25.png">

**Comment by hacamer** [comment]
> > ![Screenshot_20220927-003759_Lawnchair](https://user-images.githubusercontent.com/73057402/192332957-d50a68ff-00d8-4db6-b4c6-ee1b6b9fda4d.png) 再次测试，依旧无法复现问题
> 
> 今天再看了下，挺奇怪的，这个vd6.l.qq.com网址24号是会被拦截的，今天27号我把之前自己写的允许项删除后，发现这个网址已经不再被规则拦截了。vd6.l.qq.com网址不再被拦截，这也许是你无法复现的原因。 <img alt="截屏2022-09-27 18 29 57" width="1066" src="https://user-images.githubusercontent.com/39561185/192503156-bd9d80b9-5750-45c5-b118-9257e0f11ad3.png"> <img alt="截屏2022-09-27 18 31 06" width="1031" src="https://user-images.githubusercontent.com/39561185/192503212-a9660152-8499-46b3-9520-e06a252a3e25.png">

也许吧，感谢你的测试
