### ISSUE TITLE
[误杀]导致无法打开网站，Please disable AdBlock to access this site!

### ISSUE THREAD

**Issue by maxage** [Cats-Team/AdRules#77]
域名/误拦截的东西：
使用的列表： https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt
使用的工具：https://adguard-dns.io/ 
问题描述：
打开网页提示如下
Please disable AdBlock to access this site!
被检测拦截。无法打开网页。
https://hax.co.id/
https://woiden.id/

**Comment by hacamer** [comment]
这类情况无法通过DNS过滤解决
建议使用插件

**Comment by linshengxuan** [comment]
> 此类情况无法通过 DNS 过滤解决 建议使用插件
什么插件啊
