### ISSUE TITLE
[误杀] docker 官方软件源被误杀

### ISSUE THREAD

**Issue by FanxJK** [Cats-Team/AdRules#78]
域名/误拦截的东西：docker 官方软件源被误杀
使用的列表： DNS拦截列表：AdRules DNS List , DNS 允许列表: AdRules Allowlist
使用的工具：AdGuard Home
问题描述：
docker 官方软件源被误杀
将: `download.docker.com` 加白后正常

错误原因：
由于`download.docker.com` 是CNAME解析到 `d2h67oheeuigaw.cloudfront.net` 所以匹配到 `https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt` 的
```
||cloudfront.net^
```
> `cloudfront.net` 作为 AWS 的 CDN 服务，以一刀切的方式进行拦截是否不太合适？

截图:
![屏幕截图 2022-09-26 104347](https://user-images.githubusercontent.com/22773968/192183953-c2b3e335-8baf-4554-ba35-b487e8e6ccbd.png)
![image_2022-09-26_10-37-08](https://user-images.githubusercontent.com/22773968/192183980-61809fb3-c9e9-4b7f-b53b-e5131e8b4263.png)

**Comment by FanxJK** [comment]
补充: `https://hub.docker.com` 也大量使用到 `cloudfront` 服务
![屏幕截图 2022-09-26 110450](https://user-images.githubusercontent.com/22773968/192185968-aa7cd9a3-a6a3-43d2-a881-8cb7bc3a87f0.png)

**Comment by GizmoOAO** [comment]
其他的一些服务也受到了影响，比如 `download-installer.cdn.mozilla.net` 和 `files.vrchat.cloud`

**Comment by hacamer** [comment]
@GizmoOAO @FanxJK 两位 更新下规则试试？
9月26日18：55分 似乎没看到这个问题

**Comment by SakuraFallingMad** [comment]
https://livedoor.blogimg.jp/

**Comment by hacamer** [comment]
怪事 我稍后查看是哪个上游误杀了

**Comment by hacamer** [comment]
@GizmoOAO @FanxJK 感谢二位久等，已经解决这个问题，请更新规则
如还有问题可再次打开该issue
