### ISSUE TITLE
新的dnsfilter在adguard上出现问题

### ISSUE THREAD

**Issue by asky88** [Cats-Team/AdRules#8]
adguard的dns语法似乎不支持重定向规则，全部视为拦截
![Screenshot_2021-11-08-08-31-33-691_com adguard android](https://user-images.githubusercontent.com/82694610/140668073-f523049c-1e11-4138-be90-4230c19f001d.jpg)

**Comment by hacamer** [comment]
这是AdGuard的表述不清晰，实际上是已经返回这个ip，你可以ping一下

**Comment by asky88** [comment]
我在开着dnsfilter的情况下，用miui浏览器打开github.com显示ERR_NAME_NOT_RESOLVED，关掉dnsfilter就可以开了，而且adguard的日志里也只有这一条和github有关的。主观感觉应该是识别成拦截规则了

**Comment by Unkingh** [comment]
用酷安时复现了该问题，同样是在关闭 dnsfilter 后恢复正常
![Screenshot_20211109-171040](https://user-images.githubusercontent.com/36095707/140900779-04fa9781-7b5b-4731-894a-83cc59f7fe79.jpg)
![Screenshot_20211109-171124](https://user-images.githubusercontent.com/36095707/140900784-1474030f-693c-444e-8171-76cd4a910097.jpg)

**Comment by hacamer** [comment]
已修复！请更新规则
