### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by Vulcankta** [Cats-Team/AdRules#81]
域名/误拦截的东西：
使用的列表： AdRules AdBlock List Full
使用的工具：AdGuard Home
问题描述：https://i.postimg.cc/8c9YrgVR/Very-Capture-20221015192600.png

误杀的规则(可选):AdRules AdBlock List Full

**Comment by DoingDog** [comment]
图片的链接打不开了

**Comment by DoingDog** [comment]
抱歉是我的网络问题

**Comment by hacamer** [comment]
https://github.com/damengzhu/banad/commit/f157a948bebd6d6af101d4b55ba9b908466eb246
上游已修复
更新规则即可
