### ISSUE TITLE
[新增拦截]一个能引起dns污染的域名

### ISSUE THREAD

**Issue by Bitcion** [Cats-Team/AdRules#83]
使用的列表:
域名/链接: wvvw-rfi-fr-cddc.at-o.net
出现场景：访问rfi.fr随机出现
使用工具:adguardhome
补充说明：访问rfi.fr时经常出现w v v w的域名，一个经常出现的是w v v w.rfi.fr（已经在拦截列表中）。证书与官网不一致，只要记录中出现这个域名，那所有rfi.fr官方的网页都不能打开（无法建立安全连接），不过可能是ipv4反污染机制，这种场景只出现在ipv4透明代理+ipv6直连，即ipv6直连失败后跳回ipv4翻墙。但是出现在w v v w后无法跳回v4然后进入代理，可能是ipv6直连或者证书方面其他原因。
介于w v v w多为域名钓鱼使用，可否用通用规则屏蔽。
若不能先增加wvvw-rfi-fr-cddc.at-o.net。这个是今天才出现的，之前没见过

**Comment by hacamer** [comment]
@Bitcion 抱歉，近两天没怎么看信息，现在才看
你说的这种情况很奇怪，是DNS没解析正确吗？

**Comment by Bitcion** [comment]
> @Bitcion 抱歉，近两天没怎么看信息，现在才看
> 你说的这种情况很奇怪，是DNS没解析正确吗？

访问rfi.fr时dns记录里会突然出现这么个域名，猜测是这个网站与官网证书不一致？
这个域名像是dns故意返回这么个有问题的域名

**Comment by hacamer** [comment]
> > @Bitcion 抱歉，近两天没怎么看信息，现在才看
> > 你说的这种情况很奇怪，是DNS没解析正确吗？
> 
> 访问rfi.fr时dns记录里会突然出现这么个域名，猜测是这个网站与官网证书不一致？ 这个域名像是dns故意返回这么个有问题的域名

可能是你的DNS问题（？
