### ISSUE TITLE
电视端银河奇异果 失效

### ISSUE THREAD

**Issue by nb12nb34** [Cats-Team/AdRules#84]
你好，银河奇异果的过滤不行了，电视手机端没问题，望更新下规则，谢谢了

**Comment by hacamer** [comment]
据测试，官网最新版银河奇异果的影片开头广告是可以屏蔽的，不知道你是说哪里的广告🧐
PS：
安卓12L 
app版本 12.10.0.153161

**Comment by nb12nb34** [comment]
测试华为智慧屏，app一样12.10 过滤设备openwrt adplus+,规则AdRules AdBlock List，AdRules Hosts List 视频开头广告30秒 到120秒不能过滤

**Comment by hacamer** [comment]
去试试AdRule DNS List，Hosts可能过滤不完整

**Comment by hacamer** [comment]
再次测试 我这边还是能过滤

**Comment by hacamer** [comment]
有没有可能，你的智慧屏没走DNS🧐

**Comment by nb12nb34** [comment]
在电脑上用模拟器测试了。效果一样，但有时候又可以，搞得现在也查不出来原因了。。

**Comment by hacamer** [comment]
这就很迷。。。

**Comment by hacamer** [comment]
@nb12nb34 你好，问题解决没？

**Comment by nb12nb34** [comment]
没有，暂时找个了和谐的app代替了。。

**Comment by hacamer** [comment]
那这个issue先关闭了，有什么问题可以再打开
