### ISSUE TITLE
[误杀]阿里云

### ISSUE THREAD

**Issue by JunTsao** [Cats-Team/AdRules#85]
域名/误拦截的东西：
使用的列表： AdRules DNS List
使用的工具：例如AdGuard Home
问题描述：

yunqi.aliyun.com
img.alicdn.com
aliyun-page.cn-hangzhou.log.aliyuncs.com
aliyun-web-tracker.cn-zhangjiakou.log.aliyuncs.com
videocloud.cn-hangzhou.log.aliyuncs.com

**Comment by hacamer** [comment]
前两个域名没有被拦截，后面的三个域名看上去是日志。拦截后有什么影响吗？

**Comment by hacamer** [comment]
[该issue由于长期无恢复，暂时关闭，如有需要再开启]
