### ISSUE TITLE
[误杀] ​||www.google.com/search^$removeparam=~/^(q|lr)=/ 

### ISSUE THREAD

**Issue by chermy** [Cats-Team/AdRules#88]
域名/误拦截的东西：
使用的列表：AdRules AdBlock List Full
使用的工具：ublock origin
问题描述：这条规则的定义是, 只保留q和lr两个参数, 但在实际使用中, 页面会有tbm参数来表示搜索类型, 如 Images/Videos, 所以移除了此参数会无法切换到 图像/视频 标签页. 
附上正常点击时产生的链接: 
视频: https://www.google.com/search?q=re&newwindow=1&prmd=nvi&source=lnms&tbm=vid&sa=X&ved=aaa
图像: tbm=isch
新闻: tbm=nws
...

误杀的规则(可选): ​||www.google.com/search^$removeparam=~/^(q|lr)=/

建议的修改: ​||www.google.com/search^$removeparam=~/^(q|lr|tbm)=/

**Comment by hacamer** [comment]
已修正
