### ISSUE TITLE
提交规则：去除酷安不知名广告位

### ISSUE THREAD

**Issue by asky88** [Cats-Team/AdRules#9]
||coolapk.com/v6/page/dataList?$replace=/extra_entities//
||coolapk.com/v6/feed/detail?$replace=/extra_entities//

效果：
使用前1
![图片](https://user-images.githubusercontent.com/82694610/141680383-c686c4f5-4caf-4448-89af-4a894ce6dc2e.png)

使用前2
![图片](https://user-images.githubusercontent.com/82694610/141680394-60b81494-012b-47fe-8e73-b0964e66d56a.png)

使用后1
![图片](https://user-images.githubusercontent.com/82694610/141680400-22e94184-7476-4dd6-81ae-7ec780bebefb.png)

使用后2
![图片](https://user-images.githubusercontent.com/82694610/141680406-2dd1939f-e989-416f-8057-797be620e342.png)

**Comment by asky88** [comment]
使用后2放错图了，应该是这个
![图片](https://user-images.githubusercontent.com/82694610/141680473-d9f0bc25-48d0-4671-bf44-eee5b70b2e0b.png)

**Comment by hacamer** [comment]
已添加，非常感谢！
