### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by Rzuye** [Cats-Team/AdRules#90]
域名/误拦截的东西：
使用的列表：AdRules AdBlock List
使用的工具： AdGuard
问题描述：拦截魅族主题美化部分图片!
![S21108-16120212.png](https://user-images.githubusercontent.com/91575590/200513286-6f9a0596-da5b-46c6-81df-c2f9b785047f.png)
![S21108-16121710.png](https://user-images.githubusercontent.com/91575590/200513338-61f39324-3c2b-4b49-9ecb-c3840b5cf964.png)
![S21108-16224268.png](https://user-images.githubusercontent.com/91575590/200513383-e17bb0f7-d26c-4b2b-bd19-7cb5a48aba55.png)

**Comment by hacamer** [comment]
这个是广告吧

**Comment by Rzuye** [comment]
> 这个是广告吧

这个是主题专题，推荐主题的
