### ISSUE TITLE
[误杀]spotify app提示用户离线

### ISSUE THREAD

**Issue by github3C** [Cats-Team/AdRules#92]
域名/误拦截的东西：
使用的列表： AdRules AdBlock List
使用的工具：AdGuard Home
问题描述：spotify app提示用户离线, 使用流量数据则可以正常访问

误杀的规则(可选):

被拦截方式：
- [ ] 单域名拦截
- [ ] CNAME拦截

**Comment by hacamer** [comment]
@github3C 
![图片](https://user-images.githubusercontent.com/73057402/202118540-928d2aec-0f07-43d9-8313-d72a36e5fc56.png)

**Comment by github3C** [comment]
@hacamer 需要哪边的日志?我来给你找

**Comment by hacamer** [comment]
@github3C  大概是什么环境，哪个操作系统，过滤日志等等

另外AGH用户应该使用`AdRules DNS List`

我在`ReadMe`开头讲过

> - DNS过滤器请使用 AdRules DNS List

请尝试下`AdRules DNS List`

Btw 有可能是**网络问题**，是否为不同的运营商（Wi-Fi/移动数据）

**Comment by github3C** [comment]
@hacamer 好吧.
我用的是 AdRules AdBlock List, 因为之前从论坛取的就是这个规则表
晚点我尝试切换建议规则再确认下

**Comment by hacamer** [comment]
@github3C 你好！问题解决了吗？

**Comment by github3C** [comment]
> @github3C 你好！问题解决了吗？

还没验证, 暂时切换成了adg自带的规则.
先关单, 遇到问题再提交.
