### ISSUE TITLE
[误杀]安卓APP-i茅台-云购

### ISSUE THREAD

**Issue by mjyhj** [Cats-Team/AdRules#93]
域名/误拦截的东西：安卓APP-i茅台

使用的列表：
拦截
https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt
允许
https://cats-team.github.io/AdRules/allow.txt

使用的工具：AdGuard Home
问题描述：i茅台-云购-下面的茅台酒，点不进去购买页面
![1](https://user-images.githubusercontent.com/22577418/204197393-8eb80d8a-9994-41c8-9985-37a0c2acd5fc.jpg)
![2](https://user-images.githubusercontent.com/22577418/204197401-89f662b2-8739-499f-8edc-8a7550fd182f.jpg)

正常是这样
![3](https://user-images.githubusercontent.com/22577418/204197402-2d0cf664-c49b-4388-b863-00744fae167e.jpg)

误杀的规则: 
可能是
||sfp.safe.baidu.com^
||sofire.baidu.com^

自定义放行，同时允许这2个才能进入
@@||sfp.safe.baidu.com^$important
@@||sofire.baidu.com^$important

**Comment by hacamer** [comment]
@mjyhj 可以提供下ADGH的过滤日志吗？

**Comment by hacamer** [comment]
@mjyhj 该issue已15天无人回复 将自动关闭
