### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by hqwlcm** [Cats-Team/AdRules#94]
域名/误拦截的东西：
使用的列表： AdRules AdBlock Full List
使用的工具：AdGuard Home
问题描述：
![微信图片_20221202211216](https://user-images.githubusercontent.com/20880604/205300650-97a95c56-0a06-4e60-b259-958fd864b717.png)
谷歌被拦截除此之外还有游戏永劫无间 还有移动的打卡软和作设也被拦截

**Comment by hacamer** [comment]
@hqwlcm 
![图片](https://user-images.githubusercontent.com/73057402/205311795-a0544cd9-5f5a-4a40-9926-1855af8fdaa8.png)
请点击以下里面这个问号并截图，以便我们更好排查问题

**Comment by hqwlcm** [comment]
> 

![微信图片_20221203123448](https://user-images.githubusercontent.com/20880604/205423072-47566d83-9d8d-4c86-b54e-1af85402ff92.png)

**Comment by hacamer** [comment]
@hqwlcm 应该是规则不完整
另外
项目开头写了
> DNS过滤器请使用 AdRules DNS List
