### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by yaozijin** [Cats-Team/AdRules#96]
域名/误拦截的东西：
使用的列表： 
AdRules AdBlock Full List
使用的工具：
ublock origin
问题描述：
会将it狗网站中输入网址的框一起屏蔽了
但是不加这个规则又会导致首页的一个横幅广告屏蔽不了
：)
eg：
https://www.itdog.cn/ping/

误杀的规则(可选):
itdog.cn##.page-wrapper > .col-12.mb-3

**Comment by hacamer** [comment]
@yaozijin 可以截个图吗

**Comment by yaozijin** [comment]
> 

[![2022-12-05-11-58-21.png](https://i.postimg.cc/mDzPDKn4/2022-12-05-11-58-21.png)](https://postimg.cc/8JGpXXDX)
[![2022-12-05-11-57-25.png](https://i.postimg.cc/h4mJqWxb/2022-12-05-11-57-25.png)](https://postimg.cc/yWV6FGLk)

**Comment by hacamer** [comment]
@yaozijin 我查看了一下，找不到这条规则了 再试试？

**Comment by yaozijin** [comment]
> itdog.cn##.page-wrapper > .col-12.mb-3

确实，看来上游规则已经修复了
