### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by nonfxck** [Cats-Team/AdRules#97]
域名/误拦截的东西：
使用的列表： CHN: AdRules DNS List
使用的工具：AdGuard Home
问题描述：
![image](https://user-images.githubusercontent.com/8832304/206423989-8ce989b3-a3a1-4837-b27d-822d21ffb057.png)

![image](https://user-images.githubusercontent.com/8832304/206424104-7c094044-e776-4a8a-a776-e333b72c5dd9.png)

误杀的规则(可选):

https://mtc-remote-device.bj.bcebos.com/9C76A5A59B47827B/app.js
云真机的网页请求静态资源被拦截

被拦截方式：
- [ ] 单域名拦截
- [ ] CNAME拦截

**Comment by hacamer** [comment]
@nonfxck 我这边没看到拦截喔 你更新下规则看看

**Comment by nonfxck** [comment]
更新了现在看起来没拦截了
