### ISSUE TITLE
AdRules DNS List 一天少了将近一万规则

### ISSUE THREAD

**Issue by chermy** [Cats-Team/AdRules#98]
20221208 12:36 的时候, 规则是62894条. 
20221209 02:00 的时候, 规则是53927条. 

我是在使用金山文档网页版的时候发现的, 日常屏蔽的dw-online.ksosoft.com竟然解析了, 然后注意到cats-team的规则少了将近一万.

**Comment by hacamer** [comment]
是的，去掉了一个上游，这个上游有太多的误杀

来自ProtonMail客户端

從 Proton Mail 手機版送出

-------- 原始郵件 --------
在 2022年12月9日 02:02，chermy 寫道：

**Comment by hacamer** [comment]
@chermy 少了这个规则 [Link](https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/AdGuard/AdvertisingLite)
该规则源有一些过期的上游（造成误杀） 故此移除

昨天重构部分代码，精简屎山 
因为有些人询问上游，顺便写了`included.md `
